[default]
host = FQDNAME

        [monitor://C:\inetpub\logs\LogFiles\*\*.log]
        _TCP_ROUTING = default-autolb-group
        sourcetype=ms:iis:auto
        disabled = 0

        [WinEventLog://Security]
        disabled = 0

        [WinEventLog://Application]
        disabled = 0
        blacklist = Type='Information'

        [WinEventLog://System]
        disabled = 0
        blacklist = Type='Information'
